name: flood_rescue_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^7.0.2                    # OpenStreetMap display
  flutter_map_marker_cluster: ^1.4.0    # Marker clustering on map
  latlong2: ^0.9.1                      # LatLng utilities
  geolocator: ^13.0.3                   # For location permissions and device location
  geocoding: ^3.0.0                     # Address to coordinates and vice versa
  google_maps_flutter: ^2.11.0          # Google Maps integration (optional if needed)
  http: ^1.3.0                         # HTTP client for APIs
  provider: ^6.0.0                     # State management
  flutter_native_splash: ^2.4.5        # Splash screen generator
  flutter_svg: ^2.0.17                 # SVG image support
  firebase_core: ^3.12.1               # Firebase core SDK
  firebase_auth: ^5.5.1                # Firebase authentication
  permission_handler: ^11.3.1          # For managing permissions on Android/iOS
  url_launcher: ^6.2.5                 # For launching URLs and phone dialer
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/splash_screen.png
  image_dark: assets/images/splash_screen.png
  android: true
  ios: true
  web: true

flutter:
  assets:
    - assets/images/
    - assets/logos/

  uses-material-design: true
