name: flood_rescue_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2               # Display OpenStreetMap
  #osm_nominatim: ^5.0.0             # Convert address ↔ coordinates
  #osrm: ^5.25.0                      # Routing & navigation
  flutter_map_marker_cluster: ^1.4.0 # Cluster markers on map
  latlong2: ^0.9.1                  # Handle latitude & longitude coordinates
  geolocator: ^13.0.3            # Ensure this is updated
  google_maps_flutter: ^2.11.0    # Use the latest stable version
  http: 1.3.0                   # Use a compatible version of http
  provider: ^6.0.0               # State management
  flutter_native_splash: ^2.4.5   # Splash screen package
  flutter_svg: ^2.0.17            # SVG support
  #cupertino_icons: ^1.0.8  # Cupertino icons for iOS
  firebase_core: ^3.12.1 # or the latest version
  firebase_auth: ^5.5.1   # or the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/splash_screen.png
  image_dark: assets/images/splash_screen.png
  android: true
  ios: true
  web: true

flutter:
  assets:
    - assets/images/
    - assets/logos/

  uses-material-design: true
